### PR TITLE
use more fitting backbone api

### PR DESCRIPTION
**Pull request by craigmichaelmartin**
This uses Collection#has to check for whether a model exists in a collection.

### CODE REVIEW

**Comment by p3drosola** [comment]
Can you explain your reasoning a little?

**Comment by craigmichaelmartin** [comment]
For using `has` vs `get`? We are checking whether a model is in a collection. Collection#has offers a more readable and intuitive api for doing this. No need for an `already_here` variable calling out the purpose of the `get`. Collection#get was originally chosen because there was no collection#has.

**Comment by p3drosola** [comment]
so the follow up question would be: what version was #has introduced in?

**Comment by craigmichaelmartin** [comment]
1.3, hence the peer dependency [specification ](https://github.com/p3drosola/Backbone.VirtualCollection/pull/96/commits/d62dffa7e2752a010828d936612998bf3239e411#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R37)

**Comment by p3drosola** [comment]
I think that's unnecessarily strict. I'm quite sure it works with older versions right now. There's no reason to drop support for older versions just to use a method name that's a little prettier.

**Comment by craigmichaelmartin** [comment]
Thanks for your feedback. That makes sense. Feel free to re-open in the future if you depend on a post 1.3 version of Backbone for other reasons.

**Pull request closed without merging**
