### PR TITLE
Use different UMD wrapper to add deps and add gulp for running build & tests. 

### PR DESCRIPTION
**Pull request by jacobbuck**
I've also moved the built files to the root directory, and sources to a `/src/` directory. Also the tests now need to require the built file for it to work.

If you haven't got gulp, you'll need to `npm install -g gulp` :wink:

### CODE REVIEW

**Comment by disruptek** [comment]
I'm not sure why we lost the UMD wrapper I put in 0.5, but I'm looking forward to this going in so I can use 0.6.  Thank you!

**Comment by jacobbuck** [comment]
@disruptek At the moment Browserify is adding a UMD wrapper (using standalone mode), however it doesn't accomodate for AMD dependancies.

**Comment by p3drosola** [comment]
ok. looks good. nice PR @jacobbuck

**Comment by masylum** [comment]
jacobbuck is the new jackbach

**Comment by jacobbuck** [comment]
sweet, thanks.

**Comment by jacobbuck** [comment]
@disruptek Good spotting. I've fixed this in #67 :smile:

**Pull request merged**
