### PR TITLE
specify backbone as a peer dependency

### LINKED ISSUE #95: make backbone a peer dependency
Is there a reason backbone is listed as a dependency, rather than a peer dependency?

### PR DESCRIPTION
**Pull request by craigmichaelmartin**
closes #95

### CODE REVIEW

**Comment by p3drosola** [comment]
Done.

**Comment by craigmichaelmartin** [comment]
Any reason you didn't just merge this?

**Comment by p3drosola** [comment]
yeah, I removed gulp, so it had a merge conflict. was easier to do it directly than resolve it

**Comment by p3drosola** [comment]
also, if you remove the deps from package.json then the travis build won't install them, so I tweaked that as well

**Comment by craigmichaelmartin** [comment]
Cool! This PR wouldn't have removed backbone and underscore, it would have made them dev dependencies. I see you added them to the travis config. I think they are better suited as dev dependencies so that we can run tests locally as well. I made a [PR](https://github.com/p3drosola/Backbone.VirtualCollection/pull/97). Feel free to weigh in there.

**Pull request closed without merging**
