### PR TITLE
Added the url collection method to the proxied methods list

### PR DESCRIPTION
**Pull request by mllocs**
Yep.

### CODE REVIEW

**Comment by p3drosola** [comment]
Looks good... but the tests don't seem to be passing :/

**Comment by masylum** [comment]
:+1: lol

**Comment by mllocs** [comment]
the specs https://github.com/p3drosola/Backbone.VirtualCollection/pull/74

**Comment by mllocs** [comment]
BTW, should I push the changes on /backbone.virtual-collection.js too?

**Comment by p3drosola** [comment]
@mllocs Yep! the instructions are here https://github.com/p3drosola/Backbone.VirtualCollection/wiki/Release-Process

**Comment by p3drosola** [comment]
Thanks @mllocs. Just published 0.6.7 via npm. https://github.com/p3drosola/Backbone.VirtualCollection/wiki/Changelog#067

**Comment by mllocs** [comment]
Great! Thanks @p3drosola!

**Comment by mllocs** [comment]
Isn't time for VirtualCollection 4.0.0?

**Comment by p3drosola** [comment]
lol

**Pull request merged**
